DBTOOL_INCL =  -I../../../../include
DBTOOL_LIBOBJ = ../../../../lib/except.o

first:
	@CC="$(CC)" sh ../makedefs

include Makefile.sleuthkit

all: dbtool

dbtool: dbtool.c
	$(CC) $(INCL) $(CFLAGS) $(DBTOOL_INCL) $@.c -o $@ $(LIB) $(LIBS) $(SYSLIBS) $(DBTOOL_LIBOBJ)
