.TH PYFLAG 1 2005-02-27 "GNU" "PyFLAG Manual"
.SH NAME
pyflag \- python Forensic Log Analysis GUI
.SH SYNOPSIS
.B pyflag [
.I options
.B ] 
.SH DESCRIPTION
.B pyflag
starts the python Forensic Log Analysis GUI serving HTTP on the local host.  Use the --help option to list the options available (This may vary from version to version).

The first time python is run, a config file
.I .pyflagrc
needs to created in the user's home directory.  This can be achieved using the GUI by pointing a web browser to
.I http://127.0.0.1:8000
and entering the details as prompted by pyFLAG (see below for details).  This process will create the
.I .pyflagrc
file in the users home directory in the correct format.  pyFLAG must then be restarted.

.SH FILES AND DIRECTORIES
PyFLAG will read its settings from the following files in this order:
.IP \fI${prefix}/etc/pyflagrc\fP
System wide configuration file - this file contains all the required default settings.
.PP
.IP \fI~/.pyflagrc\fP
The users individual pyflagrc file - will override the system default. This file typically contains database connection credentials.
.PP
.IP "Command line options"\fP
The command line options override all other parameters.

.SH EXAMPLE
$ pyflag ----httpserver_port=9000
.SH "SEE ALSO"
.BR python (1),
.BR mysql (1)
.SH REQUIREMENTS
The python Forensic Log Analysis GUI requires
.B python
and associated MySQL interface,
.B MySQL
database

.SH LICENSE
.na
.nf
This software is distributed under the GNU Public License.

.SH AUTHOR
Michael Cohen and David Collet <pyflag-support@lists.sourceforge.net>


