#!/bin/bash
## This is a version of the launcher script which run on the src directory - paths are hard coded.

SRC_DIR=~/pyflag/
INSTALL_DIR=/var/tmp/build/pyflag/

######### END CONFIGURATION ####################

## This is required in case the prefix is not /usr/ (otherwise python
## can find it itself) 

export PYFLAG_PLUGINS=$SRC_DIR/src/plugins
export PYTHONPATH=$SRC_DIR/src/pyflag:$SRC_DIR/src/:/usr/local/lib/python2.6/site-packages/:/usr/local/lib/python2.5/site-packages/:$INSTALL_DIR/lib/python2.5/site-packages/pyflag:$INSTALL_DIR/lib/python2.4/site-packages/pyflag:$INSTALL_DIR/lib/python2.6/site-packages/pyflag

$@
