#!/bin/bash
## This is a version of the launcher script which run on the src directory - paths are hard coded.

SRC_DIR=~/pyflag/
INSTALL_DIR=/var/tmp/build/pyflag/

######### END CONFIGURATION ####################

export PYFLAG_PLUGINS=$SRC_DIR/src/plugins
export PYTHONPATH=$SRC_DIR/src/pyflag:$SRC_DIR/src/:/usr/loca/lib/python2.5/site-packages/:$INSTALL_DIR/lib/python2.5/site-packages/pyflag:/usr/loca/lib/python2.6/site-packages/:$INSTALL_DIR/lib/python2.6/site-packages/pyflag

echo $PYTHONPATH

exec /usr/bin/python $SRC_DIR/src/pyflag/pyflagsh.py --plugins=$SRC_DIR/src/plugins $@
