#!/bin/sh -e

. /usr/share/debconf/confmodule
test $DEBIAN_SCRIPT_DEBUG && set -v -x

PYFLAG_RUNDIR=/var/run/pyflagd
PYFLAG_CFGDIR=/etc/pyflag
PYFLAG_UNIX_SOCKET=$PYFLAG_RUNDIR/pyflag.sock
MYADMIN="/usr/bin/mysqladmin --socket=$PYFLAG_UNIX_SOCKET"

# to let pyflag restart after upgrades if it was manually started before
rm -f $PYFLAG_CFGDIR/dpkg__pyflag_was_running
if [ "$1" = "upgrade"  -a  -n "`$MYADMIN ping 2>/dev/null`" ]; then
  touch $PYFLAG_CFGDIR/dpkg__pyflag_was_running
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/pyflag" ]; then
	if [ -x /usr/sbin/invoke-rc.d ] ; then
		invoke-rc.d pyflag stop || exit 0
	else
		/etc/init.d/pyflag stop || exit 0
	fi
fi
# End automatically added section

