include Makefile
INCL    = -I/usr/include/python2.3/ -I. -Iwiretap/

pyethereal: pyethereal.i
	swig -python pyethereal.i
	$(LINK) -g $(INCL) $(tethereal_LDFLAGS) $@_wrap.c -shared $(tethereal_LDADD) $(LIBS) -o _$@.so

pcaptool:
	$(LINK) -g $(INCL) $(tethereal_LDFLAGS) $@.c $(tethereal_LDADD) $(LIBS) -o $@