var dependencies = [
"dojo.widget.ComboBox",
"dojo.widget.SplitContainer",
"dojo.widget.ContentPane",
"dojo.widget.TabContainer",
"dojo.widget.LinkPane",
"dojo.widget.LayoutContainer",
"dojo.widget.Tree",
"dojo.widget.TreeSelector",
"dojo.widget.TreeLoadingController",
"dojo.widget.Menu2",
"dojo.widget.Button",
"dojo.widget.Dialog",
"dojo.widget.Toolbar",
"dojo.widget.FloatingPane",
"dojo.uri.Uri",
"dojo.collections.Stack",
];
load("getDependencyList.js");
