Document: pyflag
Title: Debian pyflag Manual
Author: <insert document author here>
Abstract: This manual describes what pyflag is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pyflag/pyflag.sgml.gz

Format: postscript
Files: /usr/share/doc/pyflag/pyflag.ps.gz

Format: text
Files: /usr/share/doc/pyflag/pyflag.text.gz

Format: HTML
Index: /usr/share/doc/pyflag/html/index.html
Files: /usr/share/doc/pyflag/html/*.html

  
