%.pyd: %.c
	## The static is used to ensure that we do not require any
	## more dlls in the python modules. This solves the windows
	## dll hell.
	$(CC) -static $(AM_CFLAGS) $(PYTHON_CPPFLAGS) -I$(top_srcdir)/src/include $(PYTHON_LDFLAGS) -o $@ $(*F).c .libs/$*.a $(PYTHON_EXTRA_LIBS) $(AM_LDFLAGS)
	$(STRIP) $@

%.so: %.c
	## The static is used to ensure that we do not require any
	## more dlls in the python modules. This solves the windows
	## dll hell.
	$(CC) -shared $(AM_CFLAGS) $(PYTHON_CPPFLAGS) -I$(top_srcdir)/src/include $(PYTHON_LDFLAGS) -o $@ $? .libs/$*.a $(PYTHON_EXTRA_LIBS) $(AM_LDFLAGS)
	$(STRIP) $@